version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    react:
      patterns:
      - react
      - react-dom
    react-security:
      applies-to: security-updates
      patterns:
      - react
      - react-dom

  # Enable version updates for GitHub Actions
- package-ecosystem: "github-actions"
  # Workflow files stored in the default location of `.github/workflows`
  # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
  directory: "/"
  schedule:
    interval: "weekly"
